- name: Download Hadoop
  get_url:
    url: "{{ hadoop_link }}"
    dest: /tmp/hadoop.tar.gz

- name: Unpack Hadoop
  unarchive:
     src: /tmp/hadoop.tar.gz
     dest: /srv
     owner: hadoop
     group: hadoop
     mode: 0700

- name: Create symlink
  file:
    src: /srv/{{ hadoop_version }}
    dest: /srv/hadoop
    state: link
    owner: hadoop
    group: hadoop
    mode: 0700
