---
- hosts: all
  roles:
  - role: apt-update
    tags: ["system", "update", "dep"]
  - role: java
    tags: ["system", "java", "dep"]
  - role: disable_ipv6
    tags: ["system", "disable_ipv6", "dep"]
  - role: hadoop-dep
    tags: ["hadoop", "dep"]
  - role: hadoop-user
    tags: ["hadoop", "user"]
  - role: hadoop-base
    tags: ["hadoop", "hadoop-base"]
  - role: add-hadoop-user
    tags: ["add-hadoop-user"]
